version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: drone_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: drone_fastfood
    ports:
      - '3306:3306'
    command: ["--default-authentication-plugin=mysql_native_password","--lower_case_table_names=1"]
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h localhost -uroot -p1234']
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  db_data:
